name = "AquiferSense"
uuid = "25630b54-40aa-43ff-9b4d-c325e4f97899"
authors = ["Vitor Cantarella"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
